//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameIndustry
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public int DeveloperId { get; set; }
        public int GameId { get; set; }
        public int PublisherId { get; set; }
    
        public virtual Companies Companies { get; set; }
        public virtual Developers Developers { get; set; }
        public virtual Games Games { get; set; }
        public virtual Publishers Publishers { get; set; }
    }
}
